name: push image

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

env:
  IMAGE_NAME: dobolinux/codeblocks

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - uses: actions/checkout@v3

      - name: Log into registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: set release date
        run: |
          echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}
          echo "IMAGE_VERSION=$(curl --silent http://www.codeblocks.org/downloads/binaries/ | egrep -i "codeblocks_(2[0-9]\.[0-9]+)_amd64_stable.tar.xz" -o | head -n1 | egrep -o '(2[0-9]\.[0-9]+)')" >> ${GITHUB_ENV}

      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.IMAGE_NAME }}
          tags: |
            latest
            ${{ env.IMAGE_VERSION }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          push: true
          tags: '${{ steps.meta.outputs.tags }}'
          build-args: |
            BUILD_DATE=${{env.RELEASE_DATE }}
            VERSION_CODEBLOCKS=${{ env.IMAGE_VERSION }}